# TCL File Generated by Component Editor 11.0cb
# Fri Apr 22 14:35:29 CEST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | reconfig_mgmt "reconfig_mgmt" v1.0
# | Peter Schepers 2011.04.22.14:35:29
# | Interface towards the reconfig_mgmt of the transceiver
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module reconfig_mgmt
# | 
set_module_property DESCRIPTION "Interface towards the reconfig_mgmt of the transceiver"
set_module_property NAME reconfig_mgmt
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Peter Schepers"
set_module_property DISPLAY_NAME reconfig_mgmt
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s0
# | 
add_interface s0 avalon end
set_interface_property s0 addressAlignment DYNAMIC
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 isMemoryDevice false
set_interface_property s0 isNonVolatileStorage false
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 printableDevice false
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0

set_interface_property s0 ENABLED true

add_interface_port s0 reconfig_mgmt_address address Input 16
add_interface_port s0 reconfig_mgmt_read read Input 1
add_interface_port s0 reconfig_mgmt_readdata readdata Output 32
add_interface_port s0 reconfig_mgmt_write write Input 1
add_interface_port s0 reconfig_mgmt_writedata writedata Input 32
add_interface_port s0 reconfig_mgmt_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock reconfig_mgmt_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reconfig_mgmt_clk_reset reset Input 1
# | 
# +-----------------------------------
